import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './components/Navbar/Navbar';
import "./globals.css";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the site
export const metadata = {
  title: "Hacking The Climate",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // must be in public/
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar stays at the top */}
        <Navbar />

        {/* Main content */}
        {children}
      </body>
    </html>
  );
}

